### ISSUE TITLE
disable the randforcer calculation if a bruteforcer is on the same line

### ISSUE THREAD

**Issue by woobi3** [binidle/binidle.github.io#7]
Change the randforcers so if a bruteforcer is on the same line as a whole bunch of randforcers the calculation for the randforcer stops so the performance can increase, but the QPT still scales with the amount of randforcers

**Comment by woobi3** [comment]
QPT not CPT

**Comment by lockness-Ko** [comment]
performance is much better! thanks for the suggestion!
